dist: jammy
sudo: required
language: node_js

node_js:
  - "20"
  - "18"

services:
  - docker

cache: npm

env:
  - DOCKER_COMPOSE_VERSION=v2.10.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-${TRAVIS_OS_NAME}-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
