version: "3"
services:
  dynamodb:
    image: cnadiminti/dynamodb-local:latest
    ports:
      - "8000:8000"
  dynamodb-create:
    image: infrastructureascode/aws-cli:latest
    links:
      - dynamodb
    entrypoint: sh
    volumes:
      - ./example/:/project
      - ./example/create-tables.sh:/project/create-tables.sh:ro
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ENDPOINT_URL=http://dynamodb:8000
    command: " ./create-tables.sh"